### PR TITLE
Separate getting full, selective and location data for vehicles

### PR DESCRIPTION
**Pull request by robharman**
This change adds the ability to query individual vehicle data endpoints, with all endpoints as default, and adds a new method to directly get location data, and ensure it's ~recent. Seeks to lessen vehicle location requests when they are not needed.

Updates Vehicle.get_vehicle_data():
    - Selectively specify individual endpoints to query
    - Defaults to all endpoints to prevent breaking changes

Adds Vehicle.get_vehicle_location_data(max_age=300):
    - Queries location_data api endpoint to get location data if unavailable.
    - Wakes vehicle and gets updated location information if the cached data is older than `max_age` seconds
   
Adds two new flags to CLI:
-B --basic: Get only basic vehicle data
-G --location: Get current location (GPS) data

Minor changes:
    - Swaps most string formatting with fStrings, not panel ones since I
      can't test panel changes without a panel, and not the conversion
      ones since fStrings are less readable there.
    - Reflows lines over 80 chars, with same panel exception, most
      significantly in Vechicle.decode_vin()
    - Minor linting/spacing changes
    - Updates version to 2.9.0
    - Updates readme

### CODE REVIEW

**Comment by robharman** [comment]
Closing this as I didn't update the version in setup.cfg, so doing additional tests and making sure I didn't miss anything else. Will resubmit when I'm not sleepy.

**Comment by tdorssers** [comment]
@robharman thanks for taking the time to create this pull request. You can use 2.9.0 for the new version, as I didn't took the time to do so. Like the initial fix, you can put the parameters in the Python code. The endpoint file can be left untouched. I try to keep this file consistant with the endpoints.json file found in the Android distribution.

**Comment by robharman** [comment]
Thanks for the feedback! I updated this to include your advice and cleaned up get_location_data() as I found that long-running sessions were having issues when the location data had been removed from the cache and the vehicle was unreachable. 

I also made some minor linting edits in the final version.

**Comment by tdorssers** [comment]
Thanks Rob for these changes. Using format strings breaks Python 2.7 support and some Raspberry Pi users are probably still using that. So either we drop 2.7 or revert the fStrings. I tend to revert it.

**Comment by robharman** [comment]
Makes sense for the backward compatibility, I can revert as well and resubmit later this week, but not sure if there's any point. 

Looking at the [API change announcements](https://developer.tesla.com/docs/fleet-api#2023-11-17-vehicle-commands-endpoint-deprecation-timeline-action-required), which I didn't realize had already been flagged in https://github.com/tdorssers/TeslaPy/issues/150 when I made this PR, from Tesla make it look like TeslaPy is going to stop working in the next month or so anyhow. 

Overhauling TeslaPy to work with the new Vehicle command API or through the http proxy is likely going to be a lot of work for you, so fiddling with this may not be worth your time here. 

Feel free to close this if it's not going to help in the long-run. If you don't close it, I'll update my PR this week and submit. 

Either way, thanks for making my life easier for the last two years with this project! :)

**Pull request merged**
